'use client'

import { createTheme } from '@mui/material'
import './globals.css'
import { Raleway } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const theme = createTheme({
  typography: {
    fontFamily: 'inherit',
  },
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
